name: yamifood_restaurant
description: A Flutter restaurant delivery app with GetX and Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_bootstrap5: ^1.1.1+1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  flutter_stripe: ^10.0.0
  uuid: ^4.3.3
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/images/

  fonts:
    - family: Arbutus Slab
      fonts:
        - asset: asset/fonts/Arbutus_Slab.ttf
