name: yamifood_restaurant
description: Yamifood Restaurant | E-commerce Application
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
    
  # Firebase
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_messaging: ^14.5.0

  # Package
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_local_notifications: ^16.2.0
  font_awesome_flutter: ^10.4.0
  image_picker: ^1.0.5
  carousel_slider: ^4.2.1
  phone_form_field: ^8.1.1
  geolocator: ^10.1.0
  url_launcher: ^6.1.11
  syncfusion_flutter_charts: ^24.1.41
  multi_select_flutter: ^4.1.3
  flutter_map: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - asset/

  fonts:
    - family: Arbutus Slab
      fonts:
        - asset: asset/fonts/Arbutus_Slab.ttf
