name: yamifood_restaurant
description: Yamifood Restaurant | E-commerce Application
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
      # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
    # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  
  # UI Enhancement
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  pull_to_refresh: ^2.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/fonts/
    - asset/images/
    - asset/icons/
    - asset/animations/

  fonts:
    - family: Arbutus Slab
      fonts:
        - asset: asset/fonts/Arbutus_Slab.ttf
