// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmcjMUDmEqmHzFK8VrFqdAvT2j1m8lnQA',
    appId: '1:303117800586:android:0218938c43166fd64f0973',
    messagingSenderId: '303117800586',
    projectId: 'yamifood-restaurants',
    databaseURL: 'https://yamifood-restaurants-default-rtdb.firebaseio.com',
    storageBucket: 'yamifood-restaurants.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxvboVOhHAdnDyipXLVmEjTGn8dnHHcCk',
    appId: '1:303117800586:ios:733b4965cafa09154f0973',
    messagingSenderId: '303117800586',
    projectId: 'yamifood-restaurants',
    databaseURL: 'https://yamifood-restaurants-default-rtdb.firebaseio.com',
    storageBucket: 'yamifood-restaurants.appspot.com',
    iosClientId: '303117800586-m1t8hr1jfaaglt4dh57v0n6kncm2n60f.apps.googleusercontent.com',
    iosBundleId: 'com.example.yamifoodRestaurant',
  );
}
