// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP4TXQKLkkAIGlwv8fT92RKXlUdR4rTvk',
    appId: '1:346344856460:web:adaa749ec01224ebff94a9',
    messagingSenderId: '346344856460',
    projectId: 'yamifood-restaurants-app',
    authDomain: 'yamifood-restaurants-app.firebaseapp.com',
    storageBucket: 'yamifood-restaurants-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBybhe9rzI4ucgyAv8YMq1RnsEwupvdW-g',
    appId: '1:346344856460:android:df3971ee35596710ff94a9',
    messagingSenderId: '346344856460',
    projectId: 'yamifood-restaurants-app',
    storageBucket: 'yamifood-restaurants-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfgwyqRr8zeHWJLR82e0RxKuHn_TJEy1E',
    appId: '1:346344856460:ios:4235858e1afd1833ff94a9',
    messagingSenderId: '346344856460',
    projectId: 'yamifood-restaurants-app',
    storageBucket: 'yamifood-restaurants-app.appspot.com',
    androidClientId: '346344856460-umj916jeihbts9n2n6qd818jt4gfq9r8.apps.googleusercontent.com',
    iosBundleId: 'com.arandas.yamifoodRestaurant',
  );

}