// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for macos - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBybhe9rzI4ucgyAv8YMq1RnsEwupvdW-g',
    appId: '1:346344856460:android:c364d9d83c6e98e8ff94a9',
    messagingSenderId: '346344856460',
    projectId: 'yamifood-restaurants-app',
    storageBucket: 'yamifood-restaurants-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfgwyqRr8zeHWJLR82e0RxKuHn_TJEy1E',
    appId: '1:346344856460:ios:2b844d3224e2d59bff94a9',
    messagingSenderId: '346344856460',
    projectId: 'yamifood-restaurants-app',
    storageBucket: 'yamifood-restaurants-app.appspot.com',
    androidClientId: '346344856460-t4utb157a8fg6hi1tj9m8cj3i5pk919r.apps.googleusercontent.com',
    iosClientId: '346344856460-gun8pqp7p63gm6uqmab2t4eb3cdcj22r.apps.googleusercontent.com',
    iosBundleId: 'com.arandas.yamifoodRestaurant',
  );
}
